version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINERPORT_API=${CONTAINERPORT_API}
    #env_file:
    #  - .env
    # container_name: mini-interns-app

    env_file:
      - .env
      
    ports:
      - "${HOSTPORT_FRONTEND:-3000}:${CONTAINERPORT_FRONTEND:-3000}"
      - "6274:6274"  # MCP Inspector Web UI
      - "6277:6277"  # MCP Inspector Proxy Server
    volumes:
      - ./data/db:/data/db
      - ./data/redis:/data/redis
      - ./data/keys:/data/keys
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - qdrant
    labels:
      - "logging_job=mini-interns-app"

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    # container_name: mini-interns-qdrant
    volumes:
      - ./data/qdrant:/qdrant/storage
    ports:
      - "${HOSTPORT_QDRANT:-6333}:${CONTAINERPORT_QDRANT:-6333}" # HTTP
      - "${HOSTPORT_QDRANT_GRPC:-6334}:${CONTAINERPORT_QDRANT_GRPC:-6334}" # gRPC
    environment:
      - QDRANT__SERVICE__HTTP_PORT=${CONTAINERPORT_QDRANT:-6333} # leave left side as is, this is the required name by the qdrant server config
      - QDRANT__SERVICE__GRPC_PORT=${CONTAINERPORT_QDRANT_GRPC:-6334} # leave left side as is, this is the required name by the qdrant server config

  promtail:
    build:
      context: ./promtail
    # container_name: mini-interns-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    entrypoint: |
      /bin/sh -c '
        set -e
        INSTANCE_ID_FILE="/data/.instance_id"
        if [ ! -f "$$INSTANCE_ID_FILE" ]; then
          echo "Generating new instance ID..."
          cat /proc/sys/kernel/random/uuid > $$INSTANCE_ID_FILE
        fi
        export INSTANCE_ID=$(cat $$INSTANCE_ID_FILE)
        echo "Instance ID: $$INSTANCE_ID"

        if [ "$${DISABLE_LOG_FORWARDING:-true}" = "true" ]; then
          echo "Logging is disabled. Promtail will not start.";
          exit 0;
        else
          echo "Starting Promtail...";
          /usr/bin/promtail -config.file=/etc/promtail/config.yml -config.expand-env=true;
        fi
      '
    environment:
      - DISABLE_LOG_FORWARDING=${DISABLE_LOG_FORWARDING:-true}
    restart: unless-stopped
    depends_on:
      - app