version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINERPORT_API=${CONTAINERPORT_API}
    env_file:
      - .env
    container_name: mini-interns-app
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"
      - "6274:6274"  # MCP Inspector Web UI
      - "6277:6277"  # MCP Inspector Proxy Server
    volumes:
      - ./data/db:/data/db
      - ./data/redis:/data/redis
    dns:
      - 8.8.8.8
    restart: unless-stopped
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: mini-interns-qdrant
    volumes:
      - ./data/qdrant:/qdrant/storage