version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-interns-app
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"
    volumes:
      - ./data/db:/data/db
      - ./data/redis:/data/redis
    dns:
      - 8.8.8.8
    restart: unless-stopped 