# .github/workflows/test-compose.yml

name: Test Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run and Get Logs
        env:
          # --- PASTE ALL YOUR SECRETS HERE ---
          # This must include every variable from your config.py
          REDIS_URL: ${{ secrets.REDIS_URL }}
          CONTAINERPORT_API: ${{ secrets.CONTAINERPORT_API }}
          CONTAINERPORT_MCP_IMAP: ${{ secrets.CONTAINERPORT_MCP_IMAP }}
          CONTAINERPORT_QDRANT: ${{ secrets.CONTAINERPORT_QDRANT }}
          EMBEDDING_VECTOR_SIZE: ${{ secrets.EMBEDDING_VECTOR_SIZE }}
          EMBEDDING_OPENAI_MODEL_NAME: ${{ secrets.EMBEDDING_OPENAI_MODEL_NAME }}
          EMBEDDING_VOYAGE_API_KEY: ${{ secrets.EMBEDDING_VOYAGE_API_KEY }}
          EMBEDDING_VOYAGE_MODEL: ${{ secrets.EMBEDDING_VOYAGE_MODEL }}
          
          # These are optional but good to include
          AGENTLOGGER_ENABLE_ANONIMIZER: ${{ secrets.AGENTLOGGER_ENABLE_ANONIMIZER }}
          AGENTLOGGER_OPENROUTER_ANONIMIZER_API_KEY: ${{ secrets.AGENTLOGGER_OPENROUTER_ANONIMIZER_API_KEY }}
          AGENTLOGGER_OPENROUTER_ANONIMIZER_MODEL: ${{ secrets.AGENTLOGGER_OPENROUTER_ANONIMIZER_MODEL }}
          EMBEDDING_OPENAI_API_KEY: ${{ secrets.EMBEDDING_OPENAI_API_KEY }}
          
          # These have defaults but should be set
          DISABLE_LOG_FORWARDING: ${{ secrets.DISABLE_LOG_FORWARDING }}
          QDRANT_NAMESPACE_UUID: ${{ secrets.QDRANT_NAMESPACE_UUID }}
          
          # This one is for docker-compose.yml, not config.py
          FRONTEND_HOST_PORT: ${{ secrets.FRONTEND_HOST_PORT }}

        # This single command builds, runs, and prints all logs.
        # If any container crashes (like your 'app' container), it will stop and fail the step.
        run: docker compose up --build --abort-on-container-exit