# .github/workflows/test-compose.yml

name: Test Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        # This 'env' block makes the GitHub Secrets available as
        # environment variables for the 'docker compose' command.
        env:
          CONTAINERPORT_API: ${{ secrets.CONTAINERPORT_API }}
          # Add every other secret your compose file needs here
          # ANOTHER_VARIABLE: ${{ secrets.ANOTHER_VARIABLE }}
          # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      - name: Check running containers
        run: docker compose ps